### ISSUE TITLE
Create separate optical tracker plugin for vrep

### ISSUE THREAD

**Issue by ahundt** [ahundt/grl#23]
_From @astrick3 on February 5, 2015 21:51_

- [ ] How much can we modify in real time via the C API?
- [ ] integrate with main arm commanding loop in vrep
- [ ] so bone is moved
- [ ] arm optical tracker position is read
originally titled: Integrate optical tracking data into cut file and arm commanding loops

_Copied from original issue: ahundt/robone#23_
